{% set version = "3.5.2" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: d5a7340c30bcdf3023dd0106c8a5c430dd8fe84aeb8113bc7b93f8dd729f4af6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pythonpaste.readthedocs.io/
  summary: Tools for using a Web Server Gateway Interface stack
  license: MIT
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - kwilcox
    - daf
