{% set version = "3.5.1" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: bc80a94ca696fa733910a2fbc62a8c88971ebbcfa888bd3ee40c81835b7bfc95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pythonpaste.readthedocs.io/
  summary: Tools for using a Web Server Gateway Interface stack
  license: MIT
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - kwilcox
    - daf
