{% set version = "3.4.5" %}

package:
  name: paste
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Paste/Paste-{{ version }}.tar.gz
  sha256: de4dccf92e06d505add5a634e01d2ddb7a15a53f68c522c57531c8e69ba4bd1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six >=1.4.0

test:
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pythonpaste.readthedocs.io/
  summary: Tools for using a Web Server Gateway Interface stack
  license: MIT
  license_file: docs/license.txt

extra:
  recipe-maintainers:
    - kwilcox
    - daf
