appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: g2fvhKm0gD0mLe7IlBaxJV9piKPWitS2oFgYFSLoOPuyx+rM0jrKE5sPowQRNxN0hmkN27sQk/ZeQcUyBpLmfyucXi8Of5Ur3hi12U25VJzQkicItybKbFk8k68XPskmsT5Bwi0kg5UKOMRPb5/fiAOd2NlaPddq3sasaPBmgRRVh4Q+4ZVK07ChED10DoPDBKXk3eSoJ5N/Yms5y4WxRUWC8xgh/1GpgbymjpU4cqnUwsVvPBkj5Se97SWVfw8NLEERUiN2/duxTGXBIOUQgimgm3kHozKi7rdNp9i4Ce30uPm0aRMKEpfAf/tilKFYNvnB0jM8XXltkRJ3rV+DTj+aEzPh8NB5I8blmToIR8G02YgTgaSTG/NlWLLNeFzCyfdPOsvZNTFJK1FYnoho5U+Zs+zw0EPapJrQ5uqP/VtlEaCVskB1kM0IJiv1ptL9jhve3rbDB0uji0v5mwGRWSrL9GVDyB7+codL+6lsP3CPAbFWKuy4pAOgzUP9MHS4c/uUN2w7FLTe0yDFrvAY2DJVLlrHCs0Jzjax+JTm01QFoFc5YXIknUdLkDm9TURfXgwc6ZWyNQ01YnsjnjCqvx08mQlVZ11+WTmLE1MrCGZtmlx7Hx4527ayAMDJZUpqLAN0NqtPU0Vye0Gu73etfMk/Bg4XrGeYYlrgP1F6ANk=}
provider:
  win: azure
